export const RETURN = 'return'
export const DEPART = 'depart'
export const DIRECT = 'direct'
export const CLASS = 'class'
export const CLEAR = 'clear'
export const ONE_WAY = 'one_way'
export const ROUND_TRIP = 'round_trip'

export const ECONOMY = 'Economy'
export const BUSINESS = 'Business'