name: deploy speech-to-text
on:
  push:
    branches:
      - rush
    paths:
      - "configurations/speech-to-text/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://speechly/cli:latest
        with:
          args: deploy -a ${{ secrets.APPID_SPEECH_TO_TEXT }} configurations/speech-to-text -w
        env:
          SPEECHLY_APIKEY: ${{ secrets.SPEECHLY_APIKEY }}
